import type { BookData } from "./types"

export const booksData: BookData[] = [
  {
    id: "x-101",
    title: "X 101",
    subtitle: "The Ultimate Guide to Posting",
    author: "Guillermo Rauch",
    publishedYear: 2025,
    pages: 186,
    description: [
      "Master the art of viral content creation on X with insider strategies from one of the platform's most successful creators. Learn the psychology behind engagement and the secrets to crafting posts that resonate.",
      "From understanding algorithms to building authentic connections, Rauch reveals the proven techniques that turn ordinary thoughts into extraordinary social media moments, colloquially known as bangers.",
    ],
    genres: ["Social Media", "Marketing", "Digital Strategy"],
    rating: 4.9,
    reviews: 15623,
    materialProps: {
      color: "#000000",
      metalness: 0.8,
      roughness: 0.2,
      emissive: "#000000",
      emissiveIntensity: 0,
      texture: null,
      offsetX: -0.02,
      offsetY: 0,
    },
    backgroundColor: "#FFFFFF",
    textColor: "black",
  },
  {
    id: "we-are-so-back",
    title: "We are so back",
    subtitle: "A Manifesto for the Next Wave of Innovation",
    author: "Guillermo Rauch",
    publishedYear: 2024,
    pages: 312,
    description: [
      "In the fast-paced world of technology, failure isn't the end—it's the beginning of something greater. This is the story of resilience, innovation, and the relentless pursuit of being so back, after it being so over.",
      "Drawing from his experience building world-class developer tools and leading teams through the highs and lows of Silicon Valley, Rauch delivers a powerful manifesto rooted in being so back, while not letting it be so over.",
    ],
    genres: ["Business", "Technology", "Bestseller"],
    rating: 4.8,
    reviews: 12847,
    materialProps: {
      color: "#8B0000",
      metalness: 0.7,
      roughness: 0.3,
      emissive: "#000000",
      emissiveIntensity: 0,
      texture: null,
      offsetX: -0.01,
      offsetY: 0,
    },
    backgroundColor: "#222",
    textColor: "white",
  },
  {
    id: "vibe-coding-v0-101",
    title: "Vibe coding with v0", // removed "101" from title
    subtitle: "Building the Future with AI-Powered Development",
    author: "Guillermo Rauch",
    publishedYear: 2025,
    pages: 294,
    description: [
      "Discover the revolutionary approach to software development where artificial intelligence becomes your creative partner. Learn to harness the power of AI tools to build applications faster and more intuitively than ever before.",
      "Rauch guides you through the mindset shift from traditional coding to collaborative AI development, revealing how to maintain creativity and control while leveraging machine intelligence to amplify your capabilities.",
    ],
    genres: ["Programming", "AI", "Technology"],
    rating: 4.7,
    reviews: 9876,
    materialProps: {
      color: "#FFFFFF",
      metalness: 0.1,
      roughness: 0.8,
      emissive: "#000000",
      emissiveIntensity: 0,
      texture: null,
      offsetX: -0.01,
      offsetY: 0,
    },
    backgroundColor: "#14a8c1",
    textColor: "white",
  },
  {
    id: "how-to-say-please",
    title: "How to say please",
    subtitle: "The Art of Polite Communication in a Digital Age",
    author: "JD Vance",
    publishedYear: 2024,
    pages: 248,
    description: [
      "In our increasingly connected yet impersonal world, the simple act of saying 'please' has become a lost art. This thoughtful exploration reveals how politeness can transform relationships and open doors.",
      "Through practical examples and cultural insights, Pence demonstrates that courtesy isn't weakness—it's a superpower that can revolutionize how we interact with others, both online and offline.",
    ],
    genres: ["Self-Help", "Communication", "Psychology"],
    rating: 4.6,
    reviews: 8432,
    materialProps: {
      color: "#1E3A8A",
      metalness: 0.6,
      roughness: 0.4,
      emissive: "#000000",
      emissiveIntensity: 0,
      texture: null,
      offsetX: -0.02,
      offsetY: 0,
    },
    backgroundColor: "#1E40AF",
    textColor: "white",
  },
]
